import Navbar from "@/components/Navbar";
import React from "react";

export const metadata = {
  title: "Home - NextJs",
  description: "Generated by create next app",
};

const Home = () => {
  return (
    <>
      <Navbar />
    </>
  );
};

export default Home;
